### ISSUE TITLE
issue with the npm run start command 

### ISSUE THREAD

**Issue by Uncommon-34** [Wave-Play/robo.js#131]
i gives out this error 
![image_2023-11-13_034226498](https://github.com/Wave-Play/robo.js/assets/84247691/7af261c0-6a3a-473c-aef6-467612608c58)

**Comment by Pkmmte** [comment]
This is now resolved as of version `0.9.8`. Please upgrade to the latest version:
```bash
npx @roboplay/sage upgrade
```

Many thanks to @Nazeofel for finding the root cause.
