### ISSUE TITLE
setstate not persisting but only not everytime

### ISSUE THREAD

**Issue by Uncommon-34** [Wave-Play/robo.js#137]
i been having an issue where the set state isn't persisting after the bot is turned off and on again i have attached a screenshot of the issue. it seems to persist fine when i activate the bot using npx robo dev but when i activate the bot using npm run dev the states never persist?
![1000032723](https://github.com/Wave-Play/robo.js/assets/84247691/fac7847d-cc1c-4385-824a-e2febfde8fbe)

**Comment by Pkmmte** [comment]
Thanks for reporting this! We'll be releasing a patch fix shortly.
