### ISSUE TITLE
📚 Revamp Docs Before Major V1 Release!

### ISSUE THREAD

**Issue by alkazam-in-town** [Wave-Play/robo.js#153]
Here are some suggestions for the Robo.js docs revamp:

- [ ] Use a customizable & modern SSG framework like Nextra, Starlight or VuePress
- [ ] Follow documentation best practices for site structure and SEO
- [ ] Parralel pages for plugins comprising readme or guide
- [x] Integrate Meilisearch or Local Search
- [x] Integrate dark & white theme
- [ ] Make use of UI components like tabs, accordions, interactive examples! Using djscomponents
- [ ] Use Modern icons 
- [ ] Include modals/tooltips/popovers to explain concepts & types
- [x] Implement responsive design, accessible on all devices
- [ ] Separate Section for API Docs like djs docs, updated with workflow 
- [ ] Use reduced motion option
- [ ] Code editor integrations - highlight, copy,word highlights ,word wrap, responsive colors etc
- [ ] Include community contribute information 
- [ ] Add UI widgets for robo.js stats

**Comment by Pkmmte** [comment]
@akgang730 Awesome to see your suggestions for our docs, especially about the search engine - funny enough, I just finished setting up Meilisearch! 

Nextra does look more appealing to me over Docusaurus as we're already super familiar with Next.js and need as much flexibility as possible.

Thank you once again ✨
