### ISSUE TITLE
fix(create-robo): sometimes .gitignore isn't generated

### ISSUE THREAD

**Issue by Pkmmte** [Wave-Play/robo.js#162]
Points: 4

---

The .gitignore file is not generated when using `pnpm create robo` for some reason. This happens very often in monorepos and I believe the same is true in normal repos.

This file is supposed to have been copied from the internal `/templates` project chosen, but it is skipped for some reason. Perhaps `node:fs` doesn't like dotfiles, but only when the script is started via `pnpm` for some reason?

**Comment by Pkmmte** [comment]
It may help to work on this alongside #163 as that will give you several combinations and find the cause.

**Comment by ArnavK-09** [comment]
expierenced  this too

![image](https://github.com/Wave-Play/robo.js/assets/69188140/b6636ea6-cdfa-47f5-9d8c-e156429542b5)
