### ISSUE TITLE
Unable to Generate Invite link in JS setup

### ISSUE THREAD

**Issue by Tejas-Sharma-dev** [Wave-Play/robo.js#322]
## Issue

I'm trying to generate invite link using 'npx  robo invite' command, even though I entered ClientID and Token in .env file.

![image](https://github.com/user-attachments/assets/59b8b0aa-9d4c-4560-b52f-7987a8b25f80)

## Configurations
PS C:\Users\Tejas Sharma\Open-Source\robo-js> npx create-robo my-test-robo

<code>
        PS C:\Users\Tejas Sharma\Open-Source\robo-js> ls
        PS C:\Users\Tejas Sharma\Open-Source\robo-js> npx create-robo my-test-robo

    ✨ Welcome to Robo.js!
       Spawning my-test-robo into existence...

    📦 Creating JavaScript project
       Project created successfully with Prettier and ESLint.

    🔌 Plugin Power-Ups
       Skills acquired: Analytics, Moderation, and Web Server.

    🔑 Setting up credentials
       Get your credentials from the Discord Developer portal.

       Portal: https://discord.com/developers/applications
       Guide: https://roboplay.dev/botkey

       Manage your credentials in the .env file.

    🚀 Your Robo is ready!
       Say hello to this world, my-test-robo.

       Next steps:
       - Change directory: cd my-test-robo
       - Add missing variables: .env
       - Develop locally: npm run dev
       - Deploy to the cloud: npm run deploy
</code>

**Comment by Pkmmte** [comment]
This is now fixed in v0.10.22. Thank you for reporting it!
https://github.com/Wave-Play/robo.js/commit/db93f0aa83b78b0c17a42f275c2c74ce154a6f93
