### ISSUE TITLE
Adding a plugin via bunx 

### ISSUE THREAD

**Issue by Nazeofel** [Wave-Play/robo.js#53]
Hi I am getting that error when trying to install a plugin with bunx instead of npx.  (it doesn't work with npx either).

![image](https://github.com/Wave-Play/robo.js/assets/96749659/d3658690-7fec-4e14-8925-1977a09cc66a)

**Comment by beKoool** [comment]
Hello there, does this plugin exist?

**Comment by Nazeofel** [comment]
Fixed.
