### ISSUE TITLE
Can I contribute with a plugin and bot template and win the swag and nitro?

### ISSUE THREAD

**Issue by ArnavK-09** [Wave-Play/robo.js#59]

**Comment by 0xMouiz** [comment]
Absolutely! Contributing with a plugin and bot template would be amazing!

**Comment by 0xMouiz** [comment]
> 

Absolutely! Contributing with a plugin and bot template would be amazing!

**Comment by 0xMouiz** [comment]
> 

Absolutely! Contributing with a plugin and bot template with be amazing!

Here's the article:
https://blog.waveplay.com/hacktoberfest-with-robo-js-build-bots-or-plugins-win-cool-prizes/

And here's a tutorial to help you:
https://blog.waveplay.com/how-to-make-a-discord-robo

**Comment by ArnavK-09** [comment]
Thanks made, will contribute with the new plugin soon
