### ISSUE TITLE
Issues with FLASHCORE

### ISSUE THREAD

**Issue by ArnavK-09** [Wave-Play/robo.js#60]
unable to set or get data using flashcore, undefined

![image](https://github.com/Wave-Play/robo.js/assets/69188140/381505a9-46ed-4e91-9204-a18983b5dc03)

**Comment by ArnavK-09** [comment]
@Pkmmte can you help me a bit?

**Comment by 0xMouiz** [comment]
Hello hello,
Could you please share the entire file’s code?
It'd be better if you joined our Discord Server for Help. Here's the link:

https://discord.gg/ugdwjQvC

**Comment by ArnavK-09** [comment]
> Hello hello,
> Could you please share the entire file’s code?
> It'd be better if you joined our Discord Server for Help. Here's the link:
> 
> https://discord.gg/ugdwjQvC

👍 joined discord and sent issue
🗿 #61

**Comment by ArnavK-09** [comment]
was issues with package manager! #61
