### ISSUE TITLE
🕳 Contributors Section not Working Dynamically!

### ISSUE THREAD

**Issue by ArnavK-09** [Wave-Play/robo.js#68]
![image](https://github.com/Wave-Play/robo.js/assets/69188140/d0b0b2bd-715d-4829-9d2c-c1f61fb3c281)

**Comment by Pkmmte** [comment]
Oh yeah, I forgot that the all-contributors setup needs to be updated manually! We'd like to make this completely automated in the future via our own GitHub Robo.

@all-contributors please add @ArnavK-09 for example and plugin

**Comment by Pkmmte** [comment]
Done. ✨
