### ISSUE TITLE
refactor(sage-cli): `export` should use same Robo version as project

### ISSUE THREAD

**Issue by Pkmmte** [Wave-Play/robo.js#78]
When creating a new Robo via this command, we should pass down `--robo-version` that matches the current project's version of Robo.js. That way, we can ensure we avoid package manager hoisting issues right off the bat.

Changeset: `patch`

**Comment by Nazeofel** [comment]
Working on it, a new issues appears when passing down the version argument, it creates another folder into the main folder with the version of the robo as name.

![image.png](https://volta.s3.fr-par.scw.cloud/image_a57f42b9b0.png)

not using the version as argument:

![image.png](https://volta.s3.fr-par.scw.cloud/image_fa094b3e1a.png)

so --robo-version is most likely interfering with other options.

**Comment by Nazeofel** [comment]
Issue has been found, when passing --robo-version the first argument picked up is the robo version, enhence, create robo takes it as arg[0], found a temporary solution but waiting for further orders.

**Comment by Pkmmte** [comment]
Could it be because you're using different branches for #77 and this, so the `create-robo` version option is unavailable while you're testing this and thus `--robo-version` is rendered invalid? If that's the case, then the value for `--robo-version` would possible be used as the project name, thus causing this issue. :thonk:

**Comment by Nazeofel** [comment]
Unlikely, the tests had been made when I was working on #77, the seperation of the branches have been done after 😥

**Comment by Nazeofel** [comment]
That has been fixed.
