### ISSUE TITLE
refactor(sage-cli): `export` should use `npx install-local` by default for NPM projects

### ISSUE THREAD

**Issue by Pkmmte** [Wave-Play/robo.js#79]
NPM is quite bad at managing local dependencies, which is especially problematic for Robo.js at it is stateful at a global level. This makes installing and developing plugins *locally* a bad experience for developers because NPM decides to have multiple copies of Robo.js when there should only be one even for the same version. 

Other package managers don't have this issue, and neither does NPM workspaces. Only NPM projects without workspaces have this issue, which is unfortunately going to be most people.

For projects using npm as their package manager and not using workspaces, we should install plugins via `npx install-local` instead of `npm install` during Sage CLI's export command, after the step where we ask if they would like to install the plugin locally. This will emulate "production" (registry) installs and prevent multiple copies of Robo.js from being installed. Only downside is that watch mode will no longer work this way, so be sure to include a warning to let people know.

Changeset: `patch`

**Comment by Nazeofel** [comment]
It is correctly using, npx install-local when using npm as packagemanager.
